---
# Vagrant config.
vagrant_ip: 192.168.88.88

# Beetbox settings.
beet_project: drupal
beet_domain: "d8.local"
beet_root: "{{ beet_base }}/docroot"
beet_site_name: "Drupal 8 Sprint Box"

# Drupal settings.
drupal_create_makefile: yes
drupal_make_working_copy: true
drupal_build_makefile: yes
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"
